### ISSUE TITLE
[07_fix-feedback] logstash delimiter 이거 맞나요? 저도 테스트 해봐야 할 것 같긴 한데 잘 되면야 뭐...

### ISSUE THREAD

**Issue by qkfl2** [ParkIlHoon/data-collector#12]
https://github.com/ParkIlHoon/data-collector/blob/5e8845378441d5e1b2b6af57775a9c415684c369/logstash/pipeline/data-collect.conf#L6

요거 "
"
이거 맞나요? delimiter 는 여러개 등록 안되던가... -0- \n 도 있을것 같아서요

**Comment by ParkIlHoon** [comment]
넵 저도 처음에는 `\n` 으로 시도했었는데 의도한대로 동작하지 않아 아래 링크 참조해 현재 설정과 같은 방식으로 처리했습니다.
https://discuss.elastic.co/t/custom-file-delimiter/180957

설정 결과 아래 이미지와 같이 동일 파일에서 개행을 기준으로 데이터가 구분되었습니다.
![issue12](https://user-images.githubusercontent.com/32320659/148644734-26f1a49e-b615-4036-a4f9-aec946731e3a.png)

**Comment by qkfl2** [comment]
오~ 그렇군요! 감사합니다~
