### ISSUE TITLE
[07_fix-feedback] 혹시 이 코드가 해더를 이런식으로 가져오는 이유에 대해서 확인 해보셨을까요? ^^

### ISSUE THREAD

**Issue by qkfl2** [ParkIlHoon/data-collector#13]
https://github.com/ParkIlHoon/data-collector/blob/5e8845378441d5e1b2b6af57775a9c415684c369/src/main/java/io/hoon/datacollector/common/utils/HttpRequestUtil.java#L12

이렇게 해더를 가져오는 이유를 확인해보셨을까요? 클라이언트 IP 는 getRemoteAddr 하면 나오는데 특정 경우에 저렇게 쓰는 이유를 찾아보면 좋을것 같아서요.

그리고 그거 찾아보면서 현재 확인하는 해더를 하나만 하셨는데 그 부분도 같이 보면 좋을것 같아요
X- 의 의미는 뭔지도... ㅎㅎ.... 여기 저기서 많이 쓰여서 도움이 될 것 같아서요!

**Comment by ParkIlHoon** [comment]
클라이언트로부터의 요청이 로드밸런서나 프록시를 거치면서 `getRemoteAddr` 에서 반환하는 IP가 변경되기 때문에 추가해두었습니다!
위 경우 주로 `X-Forwarded-For` 헤더 첫번째에 최초의 아이피(클라이언트 아이피)를 세팅해두는 것으로 알고있어 해당 헤더 값을 먼저 검사하게끔 해두었습니다.

다른 헤더는 확인 후 추가해보겠습니당!
