### ISSUE TITLE
[07_fix_feedback] 요 부분 조금만 더 확인해보면 좋은 공부가 될거에요!

### ISSUE THREAD

**Issue by qkfl2** [ParkIlHoon/data-collector#17]
https://github.com/ParkIlHoon/data-collector/blob/5e8845378441d5e1b2b6af57775a9c415684c369/logstash/pipeline/data-collect.conf#L10

file_completed_action 는 delete 나 log 나 상관 없을거에요
이것보다 중요한건 

sincedb_clean_after 와 sincedb_path, start_position
요 세가지 옵션입니다~

로그스테시를 우리가 철저히 이해하고 알 필요는 없지만
이 동작방식을 이해하는건 큰 도움이 됩니다(배치에서)
왜냐하면 로그스테시가 동작하는 방식이 배치에서 아주 흔히 사용되는 패턴이기 때문이거든요(구현은 다르지만...)

이걸 알아두면 이런 패턴을 활용할 일이 있을때, (구현을 하게 되거나, 이런 패턴의 다른 라이브러리, 컴포넌트를 사용할 떄 잘 사용하거나...) 굉장히 도움이 되기 때문에... 한번 봐두면... ㅎ

**Comment by ParkIlHoon** [comment]
# file_complete_action 에 관하여 
* `file_completed_log_path` 설정 : `file_completed_action`이 log일 때 필수 설정이어서 추가했습니다.
* `file_completed_action` 설정 : delete 일 경우, 파일 쓰기 직전 파일이 제거되는 경우가 발생해 IOException을 유발해 log로 변경했습니다.

# 세 가지 옵션
* `start_position`은 `mode`가 read 일때 항상 첫 줄부터 읽는 것으로 알고있습니다.
* 나머지 옵션들은 확인해보겠습니다!
